#!/usr/bin/env python
import sys
import math
import json

from datetime import date

from workdays import net_workdays
from jira_xml import items2dict

_DEV = 'dev_done_workdays'
_PROD = 'prod_done_workdays'

#TODO: vacation and holiday support
def main(rss_feed, start_dates=None):
    '''Project looks like:
        {
            "start_dates": {
                "assignee": "2013-10-17 00:00:00",
            },
            "items": [
                {
                    "id": "str"
                    "assignee": "assignee",
                    "estimate": "small",
                    "dev_start": "2013-10-01 00:00:00",
                    "dev_done": "2013-10-02 00:00:00",
                    "prod_done": "2013-10-04 00:00:00",
                    "depends": [ "id" ]
                }
            ]
        }
    '''
    project, items = {}, []
    time_fmt = '%Y-%m-%d %H:%M:%S'
    if start_dates == "-":
        project['start_dates'] = json.load(sys.stdin)
    elif start_dates:
        with open(start_dates, 'r+U') as start_dates_f:
            project['start_dates'] = json.load(start_dates_f)

    for item in items2dict(rss_feed):
        if item.get('dev_start') and item.get('dev_done'):
            item[_DEV] = net_workdays(item['dev_start'], item['dev_done'])
        if item.get('dev_start') and item.get('prod_done'):
            item[_PROD] = net_workdays(item['dev_start'], item['prod_done'])
        for k,v in item.iteritems():
            if isinstance(v, date):
                item[k] = v.strftime(time_fmt)
        items.append(item)

    project['items'] = items
    print json.dumps(project)

if __name__ == '__main__':
    sys.exit(main(*sys.argv[1:]))
